#!/usr/bin/env bash
# ==============================================================================
# generate-index.sh - Regenerate templates/SKILLS.md and the README skill catalog
#
# Reads `metadata.category`, `metadata.tagline`, and `metadata.summary` from each
# templates/skills/<name>/SKILL.md and groups skills by templates/categories.txt.
#
# Usage: scripts/generate-index.sh [--check]
#   --check   Exit 1 if the generated files are out of date instead of writing them
# ==============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DIR="${ROOT}/templates/skills"
CATEGORIES_FILE="${ROOT}/templates/categories.txt"
INDEX_FILE="${ROOT}/templates/SKILLS.md"
README_FILE="${ROOT}/README.md"
BEGIN_MARKER="<!-- BEGIN SKILL CATALOG (generated by scripts/generate-index.sh) -->"
END_MARKER="<!-- END SKILL CATALOG -->"

CHECK=0
case "${1:-}" in
  --check) CHECK=1 ;;
  "") ;;
  *) echo "Usage: $(basename "$0") [--check]" >&2; exit 1 ;;
esac

trim() { sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'; }

# Print a frontmatter field ("name", "description", or "metadata.<key>"), unquoted.
frontmatter_field() {
  local file="$1" field="$2"
  tr -d '\r' < "${file}" | awk -v field="${field}" '
    /^---$/ { c++; if (c == 2) exit; next }
    c != 1 { next }
    /^[^[:space:]]/ { parent = "" }
    /^metadata:[[:space:]]*$/ { parent = "metadata."; next }
    {
      line = $0
      sub(/^[[:space:]]+/, "", line)
      key = line; sub(/:.*/, "", key)
      if (parent key != field) next
      val = line; sub(/^[^:]*:[[:space:]]*/, "", val)
      if (val ~ /^\x27.*\x27$/) { val = substr(val, 2, length(val) - 2); gsub(/\x27\x27/, "\x27", val) }
      else if (val ~ /^".*"$/) { val = substr(val, 2, length(val) - 2); gsub(/\\"/, "\"", val) }
      print val
      exit
    }'
}

# Load categories (order preserved).
CAT_IDS=(); declare -A CAT_TITLE CAT_INTRO CAT_COLUMN CAT_COUNT
while IFS='|' read -r id title intro column; do
  id="$(printf '%s' "${id}" | tr -d '\r' | trim)"
  [[ -z "${id}" || "${id}" == \#* ]] && continue
  CAT_IDS+=("${id}")
  CAT_TITLE[${id}]="$(printf '%s' "${title}" | trim)"
  CAT_INTRO[${id}]="$(printf '%s' "${intro}" | trim)"
  CAT_COLUMN[${id}]="$(printf '%s' "${column}" | tr -d '\r' | trim)"
  CAT_COUNT[${id}]=0
done < "${CATEGORIES_FILE}"

# Load skills and validate metadata.
declare -A INDEX_ROWS README_ROWS
errors=0
total=0
for skill_path in "${SKILLS_DIR}"/*; do
  [[ -f "${skill_path}/SKILL.md" ]] || continue
  file="${skill_path}/SKILL.md"
  dir_name="$(basename "${skill_path}")"
  name="$(frontmatter_field "${file}" name)"
  category="$(frontmatter_field "${file}" metadata.category)"
  tagline="$(frontmatter_field "${file}" metadata.tagline)"
  summary="$(frontmatter_field "${file}" metadata.summary)"

  if [[ "${name}" != "${dir_name}" ]]; then
    echo "[error] ${file}: name '${name}' does not match folder '${dir_name}'" >&2; errors=$((errors + 1))
  fi
  for field in category tagline summary; do
    if [[ -z "${!field}" ]]; then
      echo "[error] ${file}: missing metadata.${field}" >&2; errors=$((errors + 1))
    fi
  done
  if [[ -n "${category}" && -z "${CAT_TITLE[${category}]+x}" ]]; then
    echo "[error] ${file}: unknown category '${category}' (see templates/categories.txt)" >&2; errors=$((errors + 1))
    continue
  fi
  [[ -z "${category}" ]] && continue

  CAT_COUNT[${category}]=$((CAT_COUNT[${category}] + 1))
  total=$((total + 1))
  INDEX_ROWS[${category}]+="- **${dir_name}** - ${summary}"$'\n'
  README_ROWS[${category}]+="| **\`${dir_name}\`** | ${tagline//|/\\|} | ${summary//|/\\|} |"$'\n'
done
[[ ${errors} -eq 0 ]] || { echo "[error] ${errors} problem(s) found; nothing written." >&2; exit 1; }

plural() { [[ "$1" -eq 1 ]] && echo "$1 Skill" || echo "$1 Skills"; }

build_index() {
  cat <<'EOF'
# Project Skills Index

This project uses modular AI Agent Skills. Each skill lives in its own folder
(e.g., `.claude/skills/NAME/SKILL.md` or `.cursor/rules/NAME.mdc`) and is loaded
automatically by your AI coding assistant when its description matches the current task.
EOF
  for id in "${CAT_IDS[@]}"; do
    [[ ${CAT_COUNT[${id}]} -gt 0 ]] || continue
    printf '\n---\n\n## %s (%s)\n\n%s\n\n%s' "${CAT_TITLE[${id}]}" "$(plural "${CAT_COUNT[${id}]}")" \
      "${CAT_INTRO[${id}]}" "${INDEX_ROWS[${id}]}"
  done
  cat <<'EOF'

---

## Adding or Customizing Skills

Add new skills by creating a folder under `skills/<name>` with its own `SKILL.md` file.
Each `SKILL.md` must start with a YAML frontmatter block containing `name` and `description`:

```yaml
---
name: my-skill
description: Use when doing XYZ to ensure ABC standards.
---

# My Skill Title

- Guidance bullet 1
- Guidance bullet 2
```
The description is what agentic tools use to dynamically activate the skill when needed.
EOF
}

build_catalog() {
  printf '%s\n## Skill Catalog (%s Total Skills)\n' "${BEGIN_MARKER}" "${total}"
  for id in "${CAT_IDS[@]}"; do
    [[ ${CAT_COUNT[${id}]} -gt 0 ]] || continue
    printf '\n### %s (%s)\n%s\n\n| Skill | %s | What It Does |\n| :--- | :--- | :--- |\n%s' \
      "${CAT_TITLE[${id}]}" "$(plural "${CAT_COUNT[${id}]}")" "${CAT_INTRO[${id}]}" \
      "${CAT_COLUMN[${id}]}" "${README_ROWS[${id}]}"
  done
  printf '%s\n' "${END_MARKER}"
}

build_readme() {
  local catalog_file="$1"
  if ! grep -qF "${BEGIN_MARKER}" "${README_FILE}" || ! grep -qF "${END_MARKER}" "${README_FILE}"; then
    echo "[error] README.md is missing the skill catalog markers." >&2; exit 1
  fi
  tr -d '\r' < "${README_FILE}" | awk -v begin="${BEGIN_MARKER}" -v end="${END_MARKER}" -v cat_file="${catalog_file}" '
    $0 == begin { while ((getline line < cat_file) > 0) print line; skip = 1; next }
    $0 == end { skip = 0; next }
    !skip { print }'
}

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT
build_index > "${TMP_DIR}/SKILLS.md"
build_catalog > "${TMP_DIR}/catalog.md"
build_readme "${TMP_DIR}/catalog.md" > "${TMP_DIR}/README.md"

stale=0
for pair in "SKILLS.md:${INDEX_FILE}" "README.md:${README_FILE}"; do
  generated="${TMP_DIR}/${pair%%:*}"
  target="${pair#*:}"
  if tr -d '\r' < "${target}" | cmp -s - "${generated}"; then
    echo "  [same] ${target#"${ROOT}"/}"
  elif [[ ${CHECK} -eq 1 ]]; then
    echo "  [stale] ${target#"${ROOT}"/}" >&2; stale=1
  else
    cp "${generated}" "${target}"
    echo "  [ok]   ${target#"${ROOT}"/}"
  fi
done

if [[ ${stale} -eq 1 ]]; then
  echo "[error] Generated files are out of date. Run scripts/generate-index.sh" >&2
  exit 1
fi
